Favicon overrides
lilyminium/mdanalysis-sphinx-theme pull request #37
Opened 2023-09-03 21:06 UTC by ianmkenney

Allow finer control over favicons. 

Fixes #35

2023-09-04 00:09 UTC, lilyminium requested changes
Thanks for opening this, @ianmkenney! I've left some comments -- IMO we should use Sphinx's original options instead of introducing our own, as that reduces confusion on the user's part.

2023-09-04 00:09 UTC, lilyminium commented on docs/conf.py
> +    "no_favicon": False,
Sphinx has favicon and logo options already that I'd be keen to use instead of adding our own ones and confusing users. I'm not sure we need a new option here -- setting html_favicon="" and mda_official=False should be enough to make sure there's no favicon.

2023-09-04 00:09 UTC, lilyminium commented on mdanalysis_sphinx_theme/layout.html
> +{% if theme_favicon_url != '' %}
Similar to above, sphinx already has the `html_favicon` option that as I understand it turns into `favicon_url` in the theme -- see `sphinx-rtd-theme`'s handling for it https://github.com/readthedocs/sphinx_rtd_theme/blob/8ce23cec96f628ac0d29737bf1cf8cc2e750f068/sphinx_rtd_theme/layout.html#L39-L46 

IMO we should use that instead of our own theme option.

Also, IMO we should check this conditional first, so that even if we set mda_official=True we can still override by specifying our own favicon. I have similar logic for the URL in https://github.com/MDAnalysis/mdanalysis-sphinx-theme/pull/32/files .

2023-09-04 01:24 UTC, ianmkenney commented
@lilyminium I hadn't noticed those were options. I think this does what we want now

2023-09-04 04:47 UTC, lilyminium requested changes
Hm, I think this doesn't cater for all cases. If I set `mda_official: False` and have no `html_favicon` option or `html_favicon=''`, I get this error:

```
Reason: UndefinedError("'_favicon_url' is undefined")
```

The specific audience I'm thinking of is someone at the UGM who wants to have an MDAKit, but sets `mda_official: False` because it's not something we'll maintain. They have their own favicon in mind but haven't created it yet, and would rather have no favicon before they make their own. There should be a way to have nothing IMO.

On the logo side, there appears to be no way to have no logo as well. Setting `mda_official: False` and `html_logo = ""` gets me the placeholder. Personally, IMO we should maybe never default to the placeholder images. (although happy to discuss on this front!) IMO the most realistic way a user would expect to apply the theme from a cookiecutter is for us to actually explicitly set `html_logo = "_static/logos/placeholder.png"` and get them to edit it themselves.

As I linked before in #32, there's logic there that only includes a logo if `_logo_url` is defined -- that might be something to look at. In #32, setting `html_logo=""` or not setting `html_logo` results in no logo if `mda_official: False`, but gets the official logo if `mda_official: True`.

2023-09-08 08:14 UTC, lilyminium approved these changes
LGTM -- please fix the merge conflicts @ianmkenney and update CHANGELOG?

2023-09-08 08:15 UTC, lilyminium commented
Then merge when ready :)

2023-09-12 05:11 UTC, lilyminium commented
Thanks for the updates @ianmkenney -- I've marked it as "ready for review" so it's mergeable, but I'll leave it open another few days if you want to merge yourself / make any further updates.

2023-09-12 20:47 UTC, merged